# Generated by Django 4.1.4 on 2023-01-15 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 1, 15, 10, 44, 7, 782522))),
                ('phone_number', models.CharField(default=0, max_length=14)),
            ],
        ),
    ]
