# Generated by Django 4.1.4 on 2023-01-17 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 9, 30, 21, 434104)),
        ),
    ]
